/*
 * File: app/view/login_panelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.login_panelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.login_panel',
    onLoginButtonClick: function(button, e, eOpts) {
        var view = this.getView(),
            form = button.up('form'),
            values = form.getValues();

        // Success
        var successCallback = function(resp, ops) {
            debugger; 
            Ext.Msg.alert('Login success', resp);
        };
        // Failure
        var failureCallback = function(resp, ops) {

            // Show login failure error
            Ext.Msg.alert('Login Failure', resp);

        };
         Ext.Ajax.request({
        		url: "/loginCtl/login",
        		params: values,
        		success: successCallback,
        		failure: failureCallback
         });

        // Just run success for now
    }
});
