/*
 * File: app/view/OperWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Oper.view.OperWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.operwindow',

    requires: [
        'Oper.view.OperWindowViewModel',
        'Oper.view.OperWindowViewController',
        'Ext.form.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.button.Segmented'
    ],

    controller: 'operwindow',
    viewModel: {
        type: 'operwindow'
    },
    width: 400,
    closeAction: 'hide',
    title: '添加用户信息',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            defaults: {
                labelAlign: 'right'
            },
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '用户名称',
                    msgTarget: 'title',
                    name: 'username',
                    allowBlank: false,
                    blankText: '请输入用户名称',
                    regexText: '请输入用户名称'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '密码',
                    msgTarget: 'title',
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    blankText: '请输入密码'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '确认密码',
                    msgTarget: 'title',
                    name: 'topwd',
                    allowBlank: false,
                    blankText: '请输入确认密码',
                    listeners: {
                        blur: 'onTextfieldBlur'
                    }
                },
                {
                    xtype: 'radiogroup',
                    fieldLabel: '性别',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: '男',
                            checked: true
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '女'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            fieldLabel: '是否可用',
                            labelAlign: 'right',
                            boxLabel: '',
                            checked: true
                        },
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            fieldLabel: '是否为管理员',
                            labelAlign: 'right',
                            boxLabel: ''
                        }
                    ]
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    fieldLabel: '出生日期'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '中文名称',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '手机号',
                    msgTarget: 'title',
                    allowBlank: false,
                    regex: /^(1[3-8][0-9])\d{8}$/,
                    regexText: '您输入的手机号格式不正确 如：13898765432'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '邮箱',
                    inputType: 'email',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '地址'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            text: '保存',
                            listeners: {
                                click: {
                                    fn: 'onSaveButtonClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'segmentedbutton',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            formBind: false,
                            text: '取消',
                            listeners: {
                                click: {
                                    fn: 'onColsButtonClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onTextfieldBlur: function(component, event, eOpts) {
        var topwd = component.getValue();
        var form = component.up('form').getForm();
        var pwd = Ext.getCmp('tx_password').getValue();
        var toPwd = Ext.getCmp('tx_topwd').getValue();
        if(pwd != toPwd){
            Ext.Msg.alert('提示信息','您两次输入的密码不一至，请重新输入');
            Ext.getCmp('tx_password').setValue("");
            Ext.getCmp('tx_password').focus();
            Ext.getCmp('tx_topwd').setValue("");

        }
    }

});