/*
 * File: app/view/OperWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Oper.view.OperWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.operwindow',

    onSaveButtonClick: function(button, e, eOpts) {
        var form = button.up('fomr').getForm(),
            view = this.getView();
        if(form.isValid()){
            form.submit({
                success:function(fomr,action){
                    Ext.Msg.alert('Success', action.result.msg);
                    view.operwindow.hide();
                },
                failure: function(form, action) {
                    Ext.Msg.alert('Failed', action.result.msg);
                }
            });
        }
    },

    onColsButtonClick: function(button, e, eOpts) {
        button.up('operwindow').hide();
    }

});
