/*
 * File: app/view/OperContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Oper.view.OperContainer', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.operContainer',

    requires: [
        'Oper.view.OperContainerViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'opercontainer'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'gridpanel',
            autoScroll: true,
            suspendLayout: true,
            bodyBorder: false,
            title: 'Oper Grid Panel',
            forceFit: true,
            store: 'OperJsonStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    autoScroll: true,
                    width: 'auto',
                    displayInfo: true,
                    store: 'OperJsonStore'
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoScroll: true,
                    id: 'OperToolbar',
                    width: 'auto',
                    items: [
                        {
                            xtype: 'button',
                            text: '添加'
                        },
                        {
                            xtype: 'button',
                            text: '修改'
                        },
                        {
                            xtype: 'button',
                            text: '删除'
                        }
                    ]
                }
            ]
        }
    ]

});