/*
 * File: app/controller/FuncController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Func.controller.FuncController', {
    extend: 'Ext.app.Controller',
    views: [
            'FuncViewport'
        ],

    init: function(application) {
        this.control({
            '#menu_panel':{
                itemcontextmenu: this.showRightMenu,
                itemclick:this.treenodeClick
            },
            '#addRootMenu':{
            	click:'addRootMenuFn'
            }
        });
    },

    showRightMenu: function(view,record,item,index,event) {
        event.preventDefault();
        var menu = Ext.getCmp('tree_menu');
        view.select();
        menu.showAt(event.getXY());
    },
    treenodeClick:function(view,record,item,index){
    	Ext.getCmp('func_form').reset();
    	Ext.getCmp('tx_parentid').setValue(record.data.parentId);
    	Ext.getCmp('tx_id').setValue(record.getId());
    	Ext.getCmp('tx_name').setValue(record.data.text);
    	Ext.getCmp('tx_url').setValue(record.data.url);
    	
    },
    addRootMenuFn:function(t,item,e){//添加根节点
    	var menu_panel = Ext.getCmp('menu_panel');    	
    	var record = menu_panel.getSelectionModel().selected.items[0];//取得节点对像
    	var parentId = record.parentNode.getId();
    	Ext.getCmp('func_form').reset();
    	Ext.getCmp('tx_parentid').setValue(parentId);
    }

});
