/*
 * File: app/view/FuncViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Func.view.FuncViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.funcviewport',

    requires: [
        'Func.view.FuncViewportViewModel',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.form.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.button.Segmented',
        'Ext.menu.Menu'
    ],

    viewModel: {
        type: 'funcviewport'
    },
    itemId: 'headerPanel',
    layout: 'border',

    items: [
        {
	        xtype: 'treepanel',
	        region: 'west',
	        id: 'menu_panel',
	        split: true,
	        width: 231,
	        rootVisible: false,
	        store: 'MenuStore',
	        dockedItems: [{
                xtype: 'toolbar',
                dock: 'top',
                itemId: 'treeToolbar',
                width: 150,
                items: [ {
                    xtype: 'button',
                    text: '添加菜单',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: '添加根节点'
                            },
                            {
                                xtype: 'menuitem',
                                text: '添加子节点'
                            }
                        ]
                    }
                },
                {
                    xtype: 'button',
                    text: '删除'
                }]
	         }]
            
        },{
        	xtype:'menu',
        	width:120,
        	hidden:true,
        	margin: '0 0 10 0',
        	id:'tree_menu',        	
        	floating: false,
        	items: [
        	        {
        	            xtype: 'menuitem',
        	            iconCls: 'add',
        	            text: '添加根节点',
        	            id:'addRootMenu'
        	        },
        	        {
        	            xtype: 'menuitem',
        	            text: '添加子节点',
        	            id:'addSubMenu'
        	        },
        	        {
        	            xtype: 'menuitem',
        	            text: '删除',
        	            id:'delNode'
        	        }
        	    ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'contentPanel',
            items: [{
                xtype: 'form',
                id: 'func_form',
                bodyPadding: 10,                
                items: [
                    {
                        xtype: 'textfield',
                        id: 'tx_name',
                        fieldLabel: '菜单名称',
                        name: 'funcName'
                    },
                    {
                        xtype: 'textfield',
                        id: 'tx_url',
                        fieldLabel: 'URL',
                        name: 'funcURL'
                    },
                    {
                        xtype: 'textfield',
                        id: 'tx_icon',
                        fieldLabel: '图标',
                        name: 'func_icon'
                    },
                    {
                        xtype: 'radiogroup',
                        width: 400,
                        fieldLabel: '是否可用',
                        layout: {
                            type: 'hbox',
                            align: 'stretch'
                        },
                        items: [
                            {
                                xtype: 'radiofield',
                                id: 'func_isY',
                                name: 'fornavigation',
                                boxLabel: '是',
                                checked: true,
                                inputValue: '1'
                            },
                            {
                                xtype: 'radiofield',
                                id: 'func_isN',
                                name: 'fornavigation',
                                boxLabel: '否'
                            }
                        ]
                    },
                    {
                        xtype: 'textareafield',
                        id: 'tx_desc',
                        fieldLabel: '描述信息',
                        name: 'func_desc'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'tx_parentid',
                        fieldLabel: '父菜单id',
                        name: 'func_parentid',
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'tx_id',
                        fieldLabel: '菜单id',
                        name: 'func_id',
                    },
                    {
                        xtype: 'container',
                        id: 'bnt_container',
                        margin: '10 0 10 0',
                        layout: {
                            type: 'hbox',
                            align: 'middle',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: '保存'
                            },
                            {
                                xtype: 'segmentedbutton',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                text: '重置'
                            }
                        ]
                    }
                ]
            }]
        }
    ]

});