/*
 * File: app/controller/OperController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Oper.controller.OperController', {
    extend: 'Ext.app.Controller',

    refs: {
        operWindow: 'operwindow',
        operDataGrid: 'operContainer gridpanel',
		operQueryForm: 'operContainer form',
        operWinFormPanel: 'operwindow form'
    },

    control: {
        "opercontroller gridpanel": {
            select: 'onOperGridpanelSelect'
        },
		"operContainer form button[text='查询']": {
            click: 'onOperQueryFormButtonClick'
        },
        "operContainer gridpanel button[text='添加']": {
            click: 'onOperAddButtonClick'
        },
        "operContainer gridpanel button[text='修改']": {
            click: 'onOperUpdateButtonClick'
        },
        "operContainer gridpanel button[text='删除']": {
            click: 'onOperDelButtonClick'
        }
    },

    onOperGridpanelSelect: function(rowmodel, record, index, eOpts) {
        this.getViewModel().set('record',record);
    },
	onOperQueryFormButtonClick: function(button, e, eOpts) {
		  var form= button.up('form') ,grid = this.getOperDataGrid();
		  var username = form.getForm().findField('q_name').getValue();
		  var store = grid.getStore();
		  var new_params = {username:username};
		  
		  store.load({
			params:Ext.apply(store.proxy.extraParams,new_params)  
		  })
		  
    },
    onOperAddButtonClick: function(button, e, eOpts) {
        var win = this.getOperWindow();
        if(!win){
            win = Ext.create('widget.operwindow');
        }
        win.setTitle("添加用户信息");
        win.show();
        var form = this.getOperWinFormPanel();
        form.reset();

    },

    onOperUpdateButtonClick: function(button, e, eOpts) {
        var win = this.getOperWindow(),  grid = button.up("gridpanel"),mode,record;
        mode = grid.getSelectionModel();
        if(mode.getCount()<1){
            Ext.Msg.alert("提示信息","请先选择要修改的数据！");
        }else{
            if(!win){
                win = Ext.create('widget.operwindow');
            }
            win.setTitle("修改用户信息");
            win.show();
            var form = this.getOperWinFormPanel();
            form.reset();
            record = this.getViewModel().get('record');
            form.loadRecord(record);
            form.getForm().findField('username').setReadOnly(true);
            form.getForm().findField('password').setReadOnly(true);
            form.getForm().findField('topwd').setReadOnly(true);
        }

    },

    onOperDelButtonClick: function(button, e, eOpts) {
        var grid = button.up("gridpanel"),mode,record;
        mode = grid.getSelectionModel();
        if(mode.getCount()<1){
            Ext.Msg.alert("提示信息","请先选择要删除的数据！");
        }else{
            //删除数据
            Ext.Msg.confirm('确认删除', '您确认要删除选择的数据吗？', function(result) {
                if (result == 'yes') {
                    CmsAjax(
                        '/operCtl/delete',
                        {username:record.get('username')},
                        function(obj){
                            Ext.Msg.alert('提示信息',obj.message);
                            grid.getStore().load();
                        }
                    );
                }

            });
        }
    }

});
