/*
 * File: app/store/OperJsonStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Oper.store.OperJsonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'OperJsonStore',
            autoLoad: true,
            proxy: {
                type: 'ajax',
                url: '/operCtl/findOperWhereByInfo',
                reader: {
                    type: 'json',
					rootProperty:'dataRoot',
					totalProperty:'totalRows'
                }
            },
            fields: [
                {
                    type: 'string',
                    name: 'username'
                },
                {
                    type: 'string',
                    name: 'cname'
                },
                {
                    type: 'string',
                    name: 'ename'
                },
                {
                    type: 'int',
                    name: 'male'
                },
                {
                    type: 'int',
                    name: 'administrator'
                },
                {
                    type: 'string',
                    name: 'mobile'
                },
                {
                    type: 'string',
                    name: 'email'
                },
                {
                    type: 'int',
                    name: 'enabled'
                },
                {
                    type: 'date',
                    name: 'birthday'
                },
                {
                    name: 'address'
                },
                {
                    name: 'create_date'
                },
                {
                    name: 'salt'
                },
                {
                    name: 'company_id'
                }
            ]
        }, cfg)]);
    }
});