/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'MyApp.view.MainViewViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 80,
            itemId: 'headerPanel',
            layout: 'fit'
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            id: 'menu_panel',
            itemId: 'menuPanel',
            width: 200,
            padding: 0,
            layout: 'accordion',
            bodyBorder: false,
            collapseDirection: 'left',
            collapsible: true,
            title: '',
            items: [
                {
                    xtype: 'treepanel',
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            width: 'auto',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'My Panel'
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'contentTab',
            itemId: 'contentTabPanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    html: '欢迎',
                    title: '欢迎页',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'welcomePanel',
                            layout: 'fit'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'south',
            split: true,
            height: 30,
            itemId: 'southPanel'
        }
    ]

});